### ISSUE TITLE
Not really an issue! But a work around for the HW's mod dependencies.

### ISSUE THREAD

**Issue by FrostGuardian0** [LethalMods/LethalExpansionCore#1]
> As a stop-gap until there's an official solution I made a heavily de-bloated fork https://github.com/LethalMods/LethalExpansionCore which removes almost everything except the LethalSDK module loading, hopefully it serves you well!

Hello, there. As of now, the mod works perfectly. However, since most mods still have their dependencies to _this_ mod, the only way to properly use it is to have installed all 3 mods (LE, LESDK, and yours) and delete the other 2 directly from the File Explorer, since deleting them from the mod manager will bring down all other mods that depend on them. This gives all priority to the CoreModule while removing the added weight from the other mods

I don't know if there was some other place to comment, so its why I used the Issues Tab. Thanks, to the modder for doing something the other one was so dead set on not doing and making a problem out of.

Merry Christmas and Happy New Year

**Comment by 21Joakim** [comment]
Yeah I realized that might be a problem after I released it, I think I have an idea of how to work around it. I will try to get that working tomorrow!

Merry Christmas and Happy New Year to you too!

**Comment by phecdaDia** [comment]
If a mod expects LethalExpansion as a hard dependency they will have to pass the LE GUID to BepInEx to declare that. Having a separate build which, for compatibility, has the original LE GUID would work, although it's not really that pretty. 
Alternatively, I don't think there is any restriction on having two BepInEx Plugins in a single solution, but I don't know how modmanagers handle this. 
There could also be an even more stripped down version of this mod which uses the original LE GUID and has LEC as a hard dependency and simply passes all the calls to LEC so that the same mod isn't running twice. A mod manager might still download the original bloated LE, but it could then manually be replaced with the LEC "bridge". 

While already on the topic, it might be useful to also switch LEC to be in [reverse domain name notation](https://docs.oracle.com/javase/tutorial/java/package/namingpkgs.html) like the [BepInEx documentation](https://docs.bepinex.dev/articles/dev_guide/plugin_tutorial/2_plugin_start.html) recommends.

![image](https://github.com/LethalMods/LethalExpansionCore/assets/7377849/607a7994-dcab-4b7a-b585-1a4c17a3343d)

**Comment by 21Joakim** [comment]
I just updated it to be "compatible" with LethalExpansion. Now when you have both of the plugins installed it will automatically disable LethalExpansion unless the `UseOriginalLethalExpansion` option is set to `true` in which case LethalExpansionCore would be disabled instead, this should hopefully mean you can now have both as dependencies without any issues!
