### ISSUE TITLE
[Question] Not a bug, Sorry 🙏

### ISSUE THREAD

**Issue by Yominaki** [LethalMods/LethalExpansionCore#2]
Is there a way to have this but enable the time in the ship or unlimited scrap save settings?

I used expansion mostly as a dependency for scrap mods, but I also used it to get rid of some bloat so I don't have to install extra mods such as examples:

Seeing the timer in the ship,
Unlimited Items on the ship,
Swapping Ibs to kgs,

Unless the purpose of this mod was to remove those things, to lessen the load for others than I understand.
Just was wondering and trying get a better understanding of the mod, as someone that makes modpacks for friends and the public. :) 

I just saw this mod get added from another mod in my modpack so I'm sorry if this is a pointless question, I couldn't find a discord link on the page to ask this.

**Comment by 21Joakim** [comment]
Thank you for the question! The point of this fork is to keep the changes to the game as minimal as possible while still preserving the LethalSDK support (what is used to add the scrap and moons), this ensure it is much more compatible with other mods and gives you better control over what features you want and more important don't want to include in your modpack!

I personally believe it's better that every mod has a specific focus instead of adding and changing stuff left and right, even if it does mean you have to download more mods (which is made easy with things like r2modman).

Additionally this mod is fully "compatible" with LethalExpansion, if another mod requires LethalExpansionCore but you want to use LethalExpansion instead you can set the `UseOriginalLethalExpansion` config option to `true` and everything will work as it did with just LethalExpansion.

I assume you already know about mods which add the functionality you want but I will leave them here for completeness sake
https://thunderstore.io/c/lethal-company/p/ATK/ShipClock/
https://thunderstore.io/c/lethal-company/p/Drakorle/MoreItems/
https://thunderstore.io/c/lethal-company/p/Zduniusz/LBtoKG/

**Comment by Yominaki** [comment]
Thank you so much for the reply! For sure got better idea of the mod. Like I said I just saw it pop up in my modpack after an update and wanted to know more about it than was said on the thunderstore page! :) I just personally rather try to have less mods if possible especially since expansion seems to update constantly while the clock and more items doesn't really? So its kind of more reliable in my opinion cause base shipclock mod had some weird bugs with more-company for awhile as example. 

I just want to clarify cause a little confused on the wording, I don't need to set UseOriginalLethalExpansion to true if there is mods that require it right? Its just an option if I want to have it on, but not a requirement for the mods that rely on it? 

Thank you again for the hard work everyone does on modding and very much appreciated the answer!

**Comment by Yominaki** [comment]
> Thank you so much for the reply! For sure got better idea of the mod. Like I said I just saw it pop up in my modpack after an update and wanted to know more about it than was said on the thunderstore page! :) I just personally rather try to have less mods if possible especially since expansion seems to update constantly while the clock and more items doesn't really? So its kind of more reliable in my opinion cause base shipclock mod had some weird bugs with more-company for awhile as example.
> 
> I just want to clarify cause a little confused on the wording, I don't need to set UseOriginalLethalExpansion to true if there is mods that require it right? Its just an option if I want to have it on, but not a requirement for the mods that rely on it?
> 
> Thank you again for the hard work everyone does on modding and very much appreciated the answer!

Thank you so much for the reply! For sure got better idea of the mod. Like I said I just saw it pop up in my modpack after an update and wanted to know more about it than was said on the thunderstore page! :) I just personally rather try to have less mods if possible especially since expansion seems to update constantly while the clock and more items doesn't really? So its kind of more reliable in my opinion cause base shipclock mod had some weird bugs with more-company for awhile as example.

I just want to clarify cause a little confused on the wording, I don't need to set UseOriginalLethalExpansion to true if there is mods that require it right? Its just an option if I want to have it on, but not a requirement for the mods that rely on it?

Thank you again for the hard work everyone does on modding and very much appreciated the answer!

**Comment by 21Joakim** [comment]
Basically LethalExpansionCore is a mod which replaces LethalExpansion but it should be fully compatible with all mods which require LethalExpansion, the option is there because mods might require LethalExpansionCore and others might require LethalExpansion so you get the option to choose if you want the de-bloated version or the full version ensuring this mod doesn't split the userbase into two sides.

I have no idea why it would be untextured, I haven't run into anything like that. You could try to add the [LethalExpansionCoreModules](https://thunderstore.io/c/lethal-company/p/jockie/LethalExpansionCoreModules/) mod or set `LoadDefaultBundles` to `true` but I don't see how that would change anything.

Hopefully that clears it up!
